Create BlueFrontPixel.java, added reset feat ->
gwarby/Team13460for2023 pull request #15
Opened 2023-11-27 17:38 UTC by gwarby

Feat: for arm command functions, if movement of 0 is input, arm will set target position to 0. Ex: armextend(0, 0.3); arm will go to 0 tick position (resetting)

2023-11-27 18:36 UTC, lcdnbl requested changes, later dismissed
I really like the functional addition of resetting motors to 0 position.

2023-11-27 18:36 UTC, lcdnbl commented on BlueFrontPixel.java
> +public class RedBackPixel extends LinearOpMode
Line 38, RedBack -> BlueFront

2023-11-27 18:36 UTC, lcdnbl commented on BlueFrontPixel.java
> +         * LEFT: (RED BACK)
Line 169, RED BACK -> BLUE FRONT

2023-11-27 18:36 UTC, lcdnbl commented on BlueFrontPixel.java
> +         * MIDDLE: (RED BACK)
Line 203, same

2023-11-27 18:36 UTC, lcdnbl commented on BlueFrontPixel.java
> +         * RIGHT: (RED BACK)
Line 234, same

2023-11-28 03:19 UTC, gwarby commented
All 4 autonomous programs should have/use timesave functions, and arm motor reset feature

2023-12-12 16:17 UTC, merged